# Generated by Django 5.0.4 on 2024-05-01 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lastmessage_created',
            field=models.DateField(default=datetime.datetime(2024, 5, 1, 6, 47, 36, 814765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
