# Generated by Django 5.0.4 on 2024-05-03 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inbox', '0002_alter_conversation_lastmessage_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lastmessage_created',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 1, 46, 34, 621498, tzinfo=datetime.timezone.utc)),
        ),
    ]
