# Generated by Django 5.0.4 on 2024-05-28 19:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inbox', '0013_alter_conversation_lastmessage_created'),
        ('a_posts', '0011_likedreply_reply_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='share_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_posts.post'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lastmessage_created',
            field=models.DateField(default=datetime.datetime(2024, 5, 28, 19, 4, 48, 664464, tzinfo=datetime.timezone.utc)),
        ),
    ]
