# Generated by Django 5.0.4 on 2024-05-30 21:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inbox', '0014_inboxmessage_share_post_and_more'),
        ('a_posts', '0011_likedreply_reply_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lastmessage_created',
            field=models.DateField(default=datetime.datetime(2024, 5, 30, 21, 22, 41, 254081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='share_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_in_messages', to='a_posts.post'),
        ),
    ]
